### ISSUE TITLE
Non-redacted spaces

### ISSUE THREAD

**Issue by fmerz** [christiannaths/Redacted-Font#17]
thanks for this great font. I noticed, that redacted regular has blocky spaces, while the redacted script variations do not. It would be nice to have non-blocky spaces in redacted regular, too. If anyone doesn't want these they can always find and replace spaces by any other character, but if all characters are blocky you're forced to have blocks for spaces.

**Comment by alexanderknapstein** [comment]
Hi Christian, 
I think it would be great to have spaces being real space instead of a black block.
Thanks for this great wireframe-font!

**Comment by christiannaths** [comment]
Hey @alexanderknapstein and @fmerz, thanks for bringing this up.

I actually disagree with this idea. This was something I had tried early on in the design phase, and the results were very unappealing both in terms of aesthetics and also from a functional standpoint; the content was veering away from looking like it was placeholder text.

Here is a really rough mockup of how it was looking back then, hopefully you can see that this would not be a change for the better.

![screen shot 2015-01-15 at 4 57 32 pm](https://cloud.githubusercontent.com/assets/11584/5769426/9cbaae30-9cd8-11e4-9c15-29fd39f71e13.png)

If you want to submit your own mockup of this concept "done right", that might help convince me to rethink this. Otherwise, I'm gonna close this for now.

**Comment by alexanderknapstein** [comment]
Dear Christian,

thanks for your mockup. You're absolutely right. 
Best, Alex

**Comment by OlivierHokke** [comment]
Isn't that up to the designer that uses the font? Perhaps create a second version where spaces aren't redacted? Because I'd like to have a few spaces in the text. Not as many as in a normal text, but like 25~50%.

**Comment by christiannaths** [comment]
@OlivierHokke Yup! I was going to suggest using Blokk if that's the style you're after :)

**Comment by Crissov** [comment]
What about making punctuation marks (dot, comma, colon question/exclamation/quotation marks …) render as whitespace? They’re much less frequent. They should probably always collapse into one space. It could be implemented as an opt-in OT feature.

**Comment by christiannaths** [comment]
@Crissov That's a great idea actually. I'll play with how that looks and go from there. Thanks for the suggestion :)
